import 'package:drift/drift.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:volleyball_manager/core/db/tables/skill_formulas_table.dart';
import 'package:volleyball_manager/core/db/tables/outcome_curves_table.dart';
import 'package:volleyball_manager/core/db/tables/team_player_table.dart';
import 'package:volleyball_manager/features/player/data/local/player_tables.dart';
import 'package:volleyball_manager/features/team/data/local/team_tables.dart';
import 'package:volleyball_manager/features/match/data/local/matches_table.dart';
import 'package:volleyball_manager/features/match/data/local/match_audit_log_table.dart';
import 'package:volleyball_manager/features/player/data/seed/database_seeder.dart';
import 'connection.dart';

part 'database.g.dart';

final _appDatabase = AppDatabase();
final databaseProvider = Provider<AppDatabase>((ref) => _appDatabase);

@DriftDatabase(tables: [
  Players,
  Teams,
  TeamPlayers,
  SkillFormulas,
  OutcomeCurves,
  Matches,
  MatchAuditLog,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(createDriftConnection());

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
          final seeder = DatabaseSeeder(this);
          await seeder.seedAll();
        },
        onUpgrade: (m, from, to) async {
          // v2 → v3: non-destructive — add three new tables only.
          // Existing Players/Teams/SkillFormulas/OutcomeCurves rows are preserved.
          // NOTE: teamPlayers/matches/matchAuditLog accessors are generated by
          // build_runner — run `flutter pub run build_runner build` after this change.
          if (from < 3) {
            await m.createTable(teamPlayers);
            await m.createTable(matches);
            await m.createTable(matchAuditLog);
            // Seed players + teams if the table is empty
            final seeder = DatabaseSeeder(this);
            await seeder.seedPlayersAndTeams();
          }
        },
      );
}
